### PR TITLE
Add more bcd_paths; update bcd.json

### PR DESCRIPTION
**Pull request by Elchi3**
Thanks for this tool :+1:  It works great!
I've played a bit with it, so here are some more bcd_paths and a fresh bcd.json file.

### CODE REVIEW

**Comment by jcsahnwaldt** [comment]
Thanks a lot! Did you also use the tool to push data to BCD? I'd love to get some feedback / suggestions for improvement.

**Comment by Elchi3** [comment]
I did a PR against BCD now: https://github.com/mdn/browser-compat-data/pull/2711
Works really smooth so far :)

**Comment by jcsahnwaldt** [comment]
Cool! I'll have a look at the BCD PR later today. Thanks!

**Comment by jcsahnwaldt** [comment]
I just realized that there were two minor errors. Both are fixed by https://github.com/jcsahnwaldt/nct2bcd/commit/2a5033d18682b47b88db9bdd6d5f5a58f6305efd

- Duplicate entry with `bcd_path=javascript.builtins.Generator`: one for `%GeneratorPrototype%`, the other for `%GeneratorPrototype%.constructor`. Since BCD doesn't have a separate entry for the `Generator` constructor, I removed the latter entry.
  - In this case, it doesn't really matter, because the version data for the to entries is identical, but it's cleaner anyway. While one NCT entry can be mapped to multiple BCD entries (see e.g. [`"constructors require new"`](https://github.com/jcsahnwaldt/nct2bcd/blob/master/nct.json#L1908)), each `bcd_path` value should occur at most once in nct.json.
  - (I'm not even sure what `update_bcd.js` does when there are such duplicate entries. I guess the "last" entry "wins", but the meaning of "last" is probably not well-defined. Or maybe the data is merged. Either way, it's messy. :-) )
- typo: `Float32Array` should be `Float64Array`

Anyway, no big deal. Thanks again for your contribution!

**Pull request merged**
